css-two-column-layout - Jimmy Vu
Jimmy-Vu/c0821-code-solutions pull request #20
Opened 2021-08-23 16:55 UTC by Jimmy-Vu

![Screen Shot 2021-08-23 at 9 52 33 AM](https://user-images.githubusercontent.com/88172055/130486620-c0a4c1bc-2ec0-4609-bf92-91bd28b7ebce.png)

2021-08-24 00:29 UTC, codingcodymiller requested changes
Great start here! A few notes for you. Also, I see that you have that one column class you created to make space between elements, but none of your content in your `row` elements has any `column` classes to size or organize them. You should revise this to better follow the system we discussed in `css-layout-classes`

2021-08-24 00:29 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        <div class="column-one-tenth"></div>
😱 😱 😱 😱 😱 
You should _**never**_ use empty elements to create spacing. This is a job for `margin` or `padding`

2021-08-24 00:29 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      <div class="row-divider"></div>
😬

2021-08-24 00:29 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        <div class="column-one-tenth"></div>
🤢

2021-08-24 00:29 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      <div class="row-divider"></div>
`padding` or `margin`

2021-08-24 00:29 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        <div class="column-one-tenth"></div>
`padding or `margin`

2021-08-30 03:58 UTC, Jimmy-Vu commented
![Screen Shot 2021-08-29 at 8 57 04 PM](https://user-images.githubusercontent.com/88172055/131283382-485c0050-c06f-4684-b3f2-4bf2ef8e6c81.png)

2021-08-30 23:36 UTC, codingcodymiller approved these changes
Great work!!!

2021-08-30 23:38 UTC, merged