javascript-carousel - Jimmy Vu
Jimmy-Vu/c0821-code-solutions pull request #62
Opened 2021-09-16 00:44 UTC by Jimmy-Vu

https://user-images.githubusercontent.com/88172055/133531334-7a5dd313-6272-4254-9990-9375b6ceab65.mov

2021-09-16 17:12 UTC, codingcodymiller requested changes
Great start!! A couple notes for you:

2021-09-16 17:12 UTC, codingcodymiller commented on javascript-carousel/index.html
> +        </div>
Instead of making a set of dots for each image, I recommend you make one set of dots and change their classes each time the image changes.

2021-09-16 17:12 UTC, codingcodymiller commented on javascript-carousel/main.js
> +  clearInterval(carouselIntervalID);
I see you clearing the interval, but I don't see you restarting the interval anywhere. Does your carousel continue after 3 seconds when you click on a chevron or a dot?

2021-10-04 23:27 UTC, thebearingedge approved these changes

2021-10-04 23:56 UTC, merged